project: api-temp

app:
  addr: 8999
  mode: debug # debug, release, test (gin)
  read_timeout: 10s
  write_timeout: 10s

log:
  level: debug # debug, info
  console: false

db:
  driver: mysql
  database: platform
  master:
    username: root
    password: root
    address: localhost:3306
  slave:
    username: root
    password: root
    address: localhost:3306
  dial_timeout: 10s
  read_timeout: 30s
  write_timeout: 60s
  db_timezone: UTC
  app_timezone: UTC
  conn_max_life_time: 0s
  max_idle_conns: 2
  max_open_conns: 0

redis:
  address: localhost:6379
  password: ""
  db: 0

api:
  rapidash: https://rapidash.localhost
  ponyta: https://ponyta.localhost
